---
#include /includes/parameters/enable-lets-encrypt.yaml
#include /includes/catalog-icon-openshift.yaml
#include /includes/parameters/aws-region.yaml
#include /includes/parameters/purpose.yaml
#include /includes/parameters/salesforce-id.yaml
#include /includes/lifetime-standard.yaml
#include /includes/terms-of-service.yaml
#include /includes/parameters/agnosticd_open_environment.yaml
#include /includes/parameters/num-users-salesforce.yaml
# -------------------------------------------------------------------
# Mandatory Variables
# -------------------------------------------------------------------
env_type: ocp4-cluster
software_to_deploy: openshift4

# -------------------------------------------------------------------
# Platform
# -------------------------------------------------------------------
platform: rhpds



# -------------------------------------------------------------------
# OpenShift Installer Version
# -------------------------------------------------------------------
ocp4_installer_use_dev_preview: false
ocp4_installer_version: "4.12.12"
ocp4_installer_root_url: http://mirror.openshift.com/pub/openshift-v4/clients

# -------------------------------------------------------------------
# Common Password
# -------------------------------------------------------------------
common_password: "{{ (guid[:5] | hash('md5') | int(base=16) | b64encode)[:8] }}"

# -------------------------------------------------------------------
# --- Infra Workloads (YAML List)
# -------------------------------------------------------------------

infra_workloads:
- ocp4_workload_authentication
- ocp4_workload_le_certificates
- ocp4_workload_rhacs
- ocp4_workload_rhacs_authentication

# -------------------------------------------------------------------
# Workload: ocp4_workload_rhacs
# -------------------------------------------------------------------
ocp4_workload_rhacs_install_operator_channel: "rhacs-3.73"
ocp4_workload_rhacs_install_operator_starting_csv: "rhacs-operator.v3.73.1"
ocp4_workload_rhacs_install_operator_use_catalog_snapshot: true
#ocp4_workload_rhacs_install_operator_catalog_source_tag: "v4.10_2022_04_04"
ocp4_workload_rhacs_central_admin_password: "{{ common_password }}"

# -------------------------------------------------------------------
# Workload: ocp4_workload_authentication
# -------------------------------------------------------------------
ocp4_workload_authentication_idm_type: htpasswd
ocp4_workload_authentication_admin_user: dev-admin
# When no password specified it is generated
ocp4_workload_authentication_htpasswd_admin_password: "{{ common_password }}"
ocp4_workload_authentication_htpasswd_user_base: user
# When no password specified it is generated
ocp4_workload_authentication_htpasswd_user_password: openshift
ocp4_workload_authentication_htpasswd_user_count: "{{ (num_users | default('5')) | int }}"
ocp4_workload_authentication_remove_kubeadmin: true


# -------------------------------------------------------------------
# AgnosticV meta variables
# -------------------------------------------------------------------
agnosticv_meta:
  sandboxed: false
  deploy_with: babylon
  params_to_variables:
    username: student_name

# -------------------------------------------------------------------
# Babylon meta variables
# -------------------------------------------------------------------
__meta__:
  aws_sandboxed: true
  anarchy:
    namespace: babylon-anarchy-sandboxes-gpte
  catalog:
    multiuser: true
    namespace: babylon-catalog-{{ stage | default('?') }}
    display_name: RHACS Multi-user Workshop - Base Architecture
    labels:
      Provider: RHDP
      Product: Red_Hat_Advanced_Cluster_Security_Cloud_Service
      Product_Family: Red_Hat_Cloud
    parameters: []
    keywords:
    - RHACS
    - ACS
    - Latest
    - security
    - workshop
    - clustersecurity
    - advanceclustersecurity
    category: Workshops
  deployer:
    virtualenv: ansible2.9-python3.6-2021-11-30

